### ISSUE TITLE
Problems loading GIFTI files

### ISSUE THREAD

**Issue by markusadamek** [rii-mango/GIFTI-Reader-JS#2]
I have the problem that gifti files are not read correctly. Attached are a few samples which do not produce the desired output:
[Output.zip](https://github.com/rii-mango/GIFTI-Reader-JS/files/4470887/Output.zip)

These files are read correctly by [Surf Ice](https://www.nitrc.org/frs/?group_id=984)

**Comment by xgui3783** [comment]
(a year late, but hey, maybe it can be useful to someone else)

I suspect it has something to do with the `ArrayIndexingOrder` attribute. 

The reader actually faithfully reproduces the data, but the data that came out of `getData()` call will need to be massaged, depending on the visualisation software

**Comment by neurolabusc** [comment]
I suggest closing this issue. As @xgui3783 notes, the reader library correctly reports the ArrayIndexingOrder. Software that wants to read both orders will need to transpose the order of the array (e.g. xx..xyy..yzz..z -> xyzxyzxyz..). I have provides a solution for [Papaya](https://github.com/rii-mango/Papaya/pull/205/files) that can provide a template for others.
